import React, { useEffect, useState } from 'react'
import style from '../styles/Header.module.css';
import Image from 'next/image';
import Logo from '../assets/Logo1.png';
import { UilShoppingBag, UilReceipt } from '@iconscout/react-unicons';
import { useStore } from '../store/store';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';
const Header = () => {
    
    //checking the state in terminal
    // const state = useStore((state) => state)
    // console.log(state);
    const router = useRouter();
    const [Order, setOrder] = useState("")

    useEffect(() => {
        setOrder(localStorage.getItem('order'))

    }, [])
    const items = useStore((state) => state.cart.pizzas.length);

    // const gotoMenu = () =>{
    //     router.push('/');
    //     console.log(window)
    //     window.scrollTo({top: 500, left: 0, behavior: 'smooth'});

    // }

    return (
        <>
        <Head>
          <title>PIZZAVERSE</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        <div className={style.header}>
            {/* logo side */}
            <div className={style.logo}>
                <Image src={Logo} style={{borderRadius:'5px'}} alt="" width={50} height={50} />
                <span>PIZZAVERSE</span>
            </div>

            {/* menu side */}
            <ul className={style.menu}>
                <li>
                    <Link href='../'>
                        Home
                    </Link>
                </li>

                <li>
                    {/* <button onClick={gotoMenu} style={{all: 'unset'}}> */}
                    Menu
                    {/* </button> */}
                </li>

                {/* <li>Contact</li> */}
            </ul>

            {/* right side */}
            <div className={style.rightSide}>
                <Link href='/cart'>
                    <div className={style.cart}>
                        <UilShoppingBag size={35} color="#2E2E2E" />
                        <div className={style.badge}>{items}</div>
                    </div>
                </Link>

                {Order &&
                    <Link href={`/order/${Order}`}>
                        <div className={style.cart}>
                            <UilReceipt size={35} color='#2E2E2E' />
                            {Order != "" &&
                                <div className={style.badge}>
                                    {Order.length > 0 ? 1 : 0}
                                </div>}

                        </div>
                    </Link>
                }
            </div>
        </div>
        </>
    )
}

export default Header
